version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: hotel_db_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_pass
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - hotel_network

networks:
  hotel_network:
    driver: bridge
